### ISSUE TITLE
Optional - Include commits with unconventional commit messages

### ISSUE THREAD

**Issue by nthState** [requarks/changelog-action#10]
Sometimes we have commits with non-conventional commit messages, and these are excluded from the generated changelog.

It would be useful to include these in the changeling, possibly in a separate section, I imagine the action would then look like this:

```yaml
- name: Update CHANGELOG
        id: changelog
        uses: Requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}
          excludeTypes: ""
          includeUnconventionalCommits: true
```
