### ISSUE TITLE
Provided tag doesn't match latest tag

### ISSUE THREAD

**Issue by czernika** [requarks/changelog-action#14]
I'm facing issue that changelog contains changes for previous tag (1.0.6 - 1.0.7) not latest one (1.0.7 - unreleased draft 1.0.8)

This is my release list

![Снимок экрана от 2022-12-29 12-17-22](https://user-images.githubusercontent.com/86893348/209930652-6a7c5670-37cc-45b4-8863-e71dbe36a9c4.png)

Workflow steps

```
  - name: Checkout code
    uses: actions/checkout@v2

  - name: Get Next Semantic Version
    id: semver
    uses: ietf-tools/semver-action@v1
    with:
      token: ${{ secrets.GITHUB_TOKEN }}
      branch: master

  - name: Update CHANGELOG
    id: changelog
    uses: requarks/changelog-action@main
    with:
      token: ${{ secrets.GITHUB_TOKEN }}
      tag: ${{ steps.semver.outputs.current }}
      writeToFile: false

  - name: Create Release
    uses: ncipollo/release-action@v1
    with:
      allowUpdates: true
      draft: true
      name: ${{ steps.semver.outputs.next }}
      tag: ${{ steps.semver.outputs.next }}
      body: |
        ## What's Changed :eyes:

        ${{ steps.changelog.outputs.changes }}

        **Full Changelog**: https://github.com/czernika/tailwindcss-grid-area/compare//${{ steps.semver.outputs.current }}...${{ steps.semver.outputs.next }}
      token: ${{ secrets.GITHUB_TOKEN }}
```

Action passed however it is generates wrong changelist (1.0.6 - 1.0.7)

![Снимок экрана от 2022-12-29 12-17-35](https://user-images.githubusercontent.com/86893348/209930822-324205f7-5ac6-4c29-9864-23dba094aa02.png)

If I'll set next version as `tag: v1.0.8` or use range `fromTag: v1.0.7 toTag: v1.0.8` it fails

![Снимок экрана от 2022-12-29 12-22-25](https://user-images.githubusercontent.com/86893348/209930980-ac84187f-a44b-4311-af6f-3f579a4fd7dc.png)

**Comment by NGPixel** [comment]
Your steps are in the wrong order. You're trying to generate the changelog for a tag that is only created in the next step.

You need to first create the next tag (e.g. via the release-action), then generate the changelog, then update the release with the changelog:

```
  - name: Checkout code
    uses: actions/checkout@v3

  - name: Get Next Semantic Version
    id: semver
    uses: ietf-tools/semver-action@v1
    with:
      token: ${{ secrets.GITHUB_TOKEN }}
      branch: master

  - name: Create Draft Release
    uses: ncipollo/release-action@v1.12.0
    with:
      prerelease: true
      draft: false
      commit: ${{ github.sha }}
      name: ${{ steps.semver.outputs.next }}
      tag: ${{ steps.semver.outputs.next }}
      body: '*pending*'

  - name: Update CHANGELOG
    id: changelog
    uses: requarks/changelog-action@v1
    with:
      token: ${{ secrets.GITHUB_TOKEN }}
      tag: ${{ steps.semver.outputs.next }}
      writeToFile: false

  - name: Update Release
    uses: ncipollo/release-action@v1.12.0
    with:
      allowUpdates: true
      draft: false
      name: ${{ steps.semver.outputs.next }}
      tag: ${{ steps.semver.outputs.next }}
      body: |
        ## What's Changed :eyes:

        ${{ steps.changelog.outputs.changes }}

        **Full Changelog**: https://github.com/czernika/tailwindcss-grid-area/compare//${{ steps.semver.outputs.current }}...${{ steps.semver.outputs.next }}
      token: ${{ secrets.GITHUB_TOKEN }}
```
