### ISSUE TITLE
Feature Request - no valid commits should not fail

### ISSUE THREAD

**Issue by anden-dev** [requarks/changelog-action#16]
Love the action: I use it to draft release notes with `writeToFile: false`

At the moment the action will fail if there are no valid commits.

when there are no valid commits it fails with:

```sh
Error: No valid commits parsed since previous tag.
```

I would love to be able to skip the next step (for me here drafting the release) with an if like this:

```sh
if: >-
  steps.changelog.outputs.changes  != 'NA'
```

If there are no valid commits just return 'NA' or '' when not writing to file.
This could also be just an additional mode `failWhenResultEmpty: true|false` where true is the current behaviour.

Cheers,
Andreas

**Comment by rhenwinch** [comment]
hey @anden-dev,

might be an old issue but would you mind sharing (if you have one) a temporary workaround for this?

**Comment by H0R5E** [comment]
A workaround is to set `continue-on-error: true` for the step in which the action is being run. This will then convert the error into a warning. You could then maybe test if the outputs are empty or not. For example:

```yaml
      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}
        continue-on-error: true
```
