### ISSUE TITLE
PR not detected

### ISSUE THREAD

**Issue by jeacott1** [requarks/changelog-action#18]
I notice that in your latest version, referenced PR's are supposed to be linked in the changelog messages where they exist.
Its not working for me. 
when I click on the sha link I get taken to a diff page where I can clearly see the PR ref in the corner (eg: main (#16) ), so it does exist.
I'm wondering why my messages are of the format  [e0d6403] - my message (commit by @someuser) and not including the PR ref?

I'm triggering the build:
```
on:
  create:

jobs:
   myjob:
    if: (contains(github.ref, '/tags/v'))
    ...
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fromTag: ${{ github.ref_name }}
          toTag: ${{ env.previousTag }}
          excludeTypes: ""
          writeToFile: false
```
