### ISSUE TITLE
error: failed to push some refs to 'github.com:julioNico/Release-generator.git'

### ISSUE THREAD

**Issue by julioNico** [requarks/changelog-action#23]
Hello, Sorry about my question, I am learning github Action, but I need help:

I am have a problem to create a changelog on my project.

the message is: `error: failed to push some refs to 'github.com:julioNico/Release-generator.git'`

The code:

   ```
name: Generate Changelog

on:
    [push]
jobs:
     deploy:
        runs-on: ubuntu-latest


 steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ github.token }}

      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: 'docs: update CHANGELOG.md for ${{ github.ref_name }} [skip ci]'
          file_pattern: CHANGELOG.md
```
