### ISSUE TITLE
Output name in action.yml differs from actual 

### ISSUE THREAD

**Issue by cupofme** [requarks/changelog-action#29]
In [action.yaml](https://github.com/requarks/changelog-action/blob/main/action.yml) output is defined as follows:

```yaml
outputs:
  changelog:
    description: Generated changelog
```

But it is not usable and `outputs.changes` needs to be used instead. It causes confusion when using IDE extensions that rely on action.yml.
