### ISSUE TITLE
Failing to query related issues

### ISSUE THREAD

**Issue by naeben** [requarks/changelog-action#41]
Hi, 
For some reason I'm not able to query the related issues, any idea what might be the issue? 
I have the idea I'm missing something stupid (quite new to github actions).

- Initially I thought that it was a permissions issue, so I gave full permissions using `write-all` but no luck
- The new release gets created with the correct tag, but the release changelog is empty (because it can't find any issues I assume)
- I trigger the action manually for testing purposes.

Any pointers or tips are highly appreciated! 🙏 

Action:
```

name: Create SemVer Release with Conventional Commits

on:
  workflow_dispatch:

permissions: write-all


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: master

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          tag: ${{ steps.semver.outputs.next }}
          name: ${{ steps.semver.outputs.next }}
          body: Changelog Contents
          token: ${{ github.token }}

      - name: Generate CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ steps.semver.outputs.next }}
          writeToFile: false
          
      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: master
          commit_message: 'docs: update CHANGELOG.md for ${{ github.ref_name }} [skip ci]'
          file_pattern: CHANGELOG.md

```

Output:
```
Querying related issues for PR 1...
Warning: Failed to query issues related to PR 1. Skipping.
Querying related issues for PR 2...
Warning: Failed to query issues related to PR 2. Skipping.

```
