### ISSUE TITLE
Tag range to create changelog

### ISSUE THREAD

**Issue by sitepark-veltrup** [requarks/changelog-action#5]
In my case I would like to create changelogs not only for the last release but also for hotfixes further back in time.

```mermaid
%%{init: { 'gitGraph': {'showCommitLabel': false}} }%%
    gitGraph
       commit tag:"1.0.0"
       commit tag:"1.1.0"
       branch hotfix/1.1.x order:2
       checkout main
       commit tag:"..."
       commit tag:"2.0.0"
       commit tag:"2.1.0"
       branch hotfix/2.1.x order:1
       commit tag:"2.1.1"
       commit tag:"2.1.2"
       commit tag:"..."
       checkout hotfix/1.1.x
       commit tag:"1.1.1"
       commit tag:"1.1.2"
       commit tag:"..."
       checkout main
       commit tag:"..."
```

Here it would help me if instead of a tag, I could specify a range over which the changelog is generated.

I have created a [fork](https://github.com/requarks/changelog-action/compare/main...sitepark-com:main) for this purpose.

I still determine the necessary tag area for me about an extra script.

I use it like this:
``` yaml
name: Create GitHub Release Draft

on:
  push:
    tags:
      - [0-9]+.[0-9]+.[0-9]+

jobs:
  release-draft-with-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get previous tag
        id: previousTag
        run: |
          name=$(git --no-pager tag --sort=creatordate --merged ${{ github.ref_name }} | tail -2 | head -1)
          echo "previousTag: $name"
          echo "::set-output name=name::$name"

      - name: Update CHANGELOG
        id: changelog
        uses: sitepark-com/changelog-action@main
        with:
          token: ${{ github.token }}
          fromTag: ${{ github.ref_name }}
          toTag: ${{ steps.previousTag.outputs.name }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: true
          name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ secrets.GITHUB_TOKEN }}
```
But it would be more elegant if the `previousTag` would be determined in the changelog action. I haven't found a way to do this using the graphql query in the JavaScript.

Would this be a feature that could be merged?
