### ISSUE TITLE
BUG: It seems no supports for post tag

### ISSUE THREAD

**Issue by fu050409** [requarks/changelog-action#52]
```
Run requarks/changelog-action@v1
Using input tag: v0.3.0-post.1
Error: Provided tag doesn't match latest tag v0.3.0-post.1.
```

My workflow is ok at other times, but failed when tag name is `v0.3.0-post.1`, is that unsupported for `-post` tag or some mistakes causes by myself?

Here is a part of my workflow file:
```
- name: Generate Changelog
  id: changelog
  uses: requarks/changelog-action@v1
  with:
    token: ${{ github.token }}
    tag: ${{ github.ref_name }}
    includeInvalidCommits: true
    changelogFilePath: CHANGELOG.md
    writeToFile: true
    useGitmojis: false
```
