### ISSUE TITLE
Bug: revert prefix not picked up

### ISSUE THREAD

**Issue by nthState-Chris** [requarks/changelog-action#61]
Hi, I have a commit with this title:

```
revert: Home screen
```

And using the following changelog action

```
- name: Update CHANGELOG
        id: changelog
        uses: Requarks/changelog-action@v1.5.0
        with:
          tag: ${{ inputs.tag_name }}
          excludeTypes: ""
          includeInvalidCommits: true
```

However, the action doesn't find/include the commit.

- Is there a way I can see if this is user-error by running this locally and seeing if the commit is picked up?

Kind Regards

Chris
