### ISSUE TITLE
Bug: Commits between tags aren't found

### ISSUE THREAD

**Issue by NandoTheessen** [requarks/changelog-action#66]
Hi! 

Currently trying to make this work, but commits between tags aren't found.

Just tested this with two tags (v0.0.4 & v0.0.5) and added three commits in between them, but none of them were found.

Here's my configuration

```
- name: Generate Changelog
        if: contains(github.ref_name, '-rc') == false
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fromTag: ${{ env.previousTag }}
          toTag: ${{ github.ref_name }}
          includeInvalidCommits: true
          writeToFile: false
```

Here's what ran:

```
Run requarks/changelog-action@v1
  with:
    token: ***
    fromTag: v0.0.4
    toTag: v0.0.5
    includeInvalidCommits: true
    writeToFile: false
    excludeTypes: build,docs,other,style
    changelogFilePath: CHANGELOG.md
    includeRefIssues: true
    useGitmojis: true
    reverseOrder: false
  env:
    previousTag: v0.0.4

Using tag range: v0.0.4 to v0.0.5
Error: Couldn't find any commits between latest and previous tags.
```

Any obvious misconfiguration you can point me to?
Or is this indeed a bug?
